site_name: Appunti Concorso A040

nav:
  - Home: 'index.md'
  - 1. Elettrotecnica: '1_elettrotecnica_generale.md'
    
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js      